name: 🙋‍♂️ Question
description: Ask a question
title: "[Question]: "
labels: ["question"]
assignees:
  - arthurmolina
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a ❓ Question!
        Please check for duplicate issues and file separated requests as separated issues.
  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the issues and discussions to see if a similar question already exists.
      options:
        - label: >
            I have searched the issues and discussion and found no similar questions.
          required: true
  - type: textarea
    attributes:
      label: Question
      description: What is your question?
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our **Code of Conduct**
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true